osx_image: xcode11
language: swift
xcode_project: CountryPicker/CountryPicker.xcodeproj
script:
  - set -o pipefail && xcodebuild test -enableCodeCoverage YES -project CountryPicker/CountryPicker.xcodeproj -scheme CountryPicker -destination 'platform=iOS Simulator,OS=12.0,name=iPhone 7' ONLY_ACTIVE_ARCH=YES
after_success:
  - bash <(curl -s https://codecov.io/bash
